// lib/text-overrides.ts
// ⚠️ Fichier généré automatiquement par scripts/apply-overrides.ts
// Ne pas modifier manuellement. Éditez text-overrides.json puis relancez le script.

export const textOverrides: Record<string, string> = {
  "Aucun résultat trouvé": "Aucun résultat trouvé",
  "Aucune question ne correspond à votre recherche.": "Aucune question ne correspond à votre recherche.",
  "avis": "avis",
  "Avis clients": "Avis clients",
  "Avis Clients": "Avis Clients",
  "Avis précédent": "Avis précédent",
  "Avis suivant": "Avis suivant",
  "Basé sur": "Basé sur",
  "Catalogue": "Catalogue",
  "Catégories": "Catégories",
  "Chargement de la boutique...": "Chargement de la boutique...",
  "Chargement du catalogue...": "Chargement du catalogue...",
  "Comment ça marche ?": "Comment ça marche ?",
  "Consulter nos produits": "Consulter nos produits",
  "Contacter le vendeur": "Contacter notre équipe",
  "Contactez-nous": "Contactez-nous",
  "De la sélection à la livraison, suivez nos six étapes claires et flexibles.": "De la sélection à la livraison dans votre pays, suivez nos six étapes claires et flexibles.",
  "Découvrez comment utiliser notre site et comment se déroule l&apos;achat de nos produits.": "Découvrez comment utiliser notre site et comment se déroule l'achat de nos produits importés de Chine et de Turquie.",
  "Découvrez notre sélection exclusive des produits les plus appréciés.": "Découvrez notre sélection exclusive de produits les plus appréciés, importés directement de Chine et de Turquie.",
  "Découvrez une sélection exclusive de produits tendance.": "Découvrez une sélection exclusive de produits tendance importés de Chine et de Turquie.",
  "Demande de devis": "Demande de devis",
  "Demander un devis": "Demander un devis",
  "En stock": "Disponible",
  "Envoyez-nous un message": "Envoyez-nous un message pour toute question",
  "Espace Vendeur": "Espace Vendeur",
  "Essayez de modifier vos filtres ou votre recherche pour trouver des avis.": "Essayez de modifier vos filtres pour trouver les avis sur nos produits.",
  "étoile(s)": "étoile(s)",
  "Explorer": "Explorer",
  "Explorez nos trois univers : des véhicules performants, des meubles\r\n              élégants et des appareils électroménagers innovants.": "Explorez nos trois univers : des véhicules performants, des meubles élégants et des appareils électroménagers innovants, sélectionnés auprès des meilleurs fournisseurs chinois et turcs et livrés dans plusieurs pays.",
  "FAQ": "FAQ",
  "Fil d": "Fil d",
  "Filtres": "Filtres",
  "Horaires d'ouverture": "Horaires d'ouverture",
  "Ils nous ont fait confiance": "Ils nous ont fait confiance",
  "J'accepte les conditions d'utilisation": "J'accepte les conditions d'utilisation",
  "L&apos;excellence à portée de clic": "L'excellence à portée de clic",
  "Laisser un avis": "Laisser un avis",
  "Marquer comme utile": "Marquer comme utile",
  "Navigation": "Navigation",
  "Nos engagements qualité": "Nos engagements qualité",
  "Nos produits": "Nos produits importés",
  "Nos valeurs": "Nos valeurs : transparence, fiabilité et proximité",
  "Note :": "Note :",
  "Notre équipe": "Notre équipe",
  "Notre équipe est là pour vous aider.": "Notre équipe est là pour vous aider dans vos démarches.",
  "Notre histoire": "Notre histoire",
  "Notre mur de confiance": "Nos certificats officiels",
  "Nous contacter": "Nous contacter",
  "Page précédente": "Page précédente",
  "Page suivante": "Page suivante",
  "Pagination": "Pagination",
  "Pourquoi nous choisir ?": "Pourquoi nous choisir ?",
  "Précédent": "Précédent",
  "Produit concerné": "Produit concerné",
  "Produit introuvable.": "Produit introuvable.",
  "Produits similaires": "Produits similaires",
  "Quatre étapes simples pour trouver et acquérir le produit qu'il vous faut.": "Quatre étapes simples pour trouver et acquérir le produit qu'il vous faut.",
  "Quatre étapes simples pour trouver et acquérir le produit qu&apos;il vous faut.": "Quatre étapes simples pour trouver et acquérir le produit importé qu'il vous faut, où que vous soyez.",
  "Question sur un produit": "Question sur un produit",
  "Recevez nos offres exclusives.": "Recevez nos offres exclusives sur les prochaines arrivées de produits importés.",
  "Rechercher un produit...": "Rechercher un produit...",
  "Réinitialiser les filtres": "Réinitialiser les filtres",
  "Restez informé": "Restez informé des nouveaux arrivages",
  "Retour à l&apos;accueil": "Retour à l'accueil",
  "Rupture de stock": "Rupture de stock",
  "S&apos;abonner": "S'abonner aux alertes",
  "Service après-vente": "Service après-vente",
  "Signaler": "Signaler",
  "Soumettre mon avis": "Soumettre mon avis",
  "Suivant": "Suivant",
  "sur 5": "sur 5",
  "Trier par": "Trier par",
  "Utile": "Utile",
  "Voir détails": "Voir les détails",
  "Voir le catalogue": "Voir le catalogue",
  "Voir tous les avis": "Voir tous les avis sur nos produits",
  "Votre commentaire": "Votre commentaire sur ce produit",
  "Votre note": "Votre note sur ce produit",
  "Vous ne trouvez pas votre réponse ?": "Vous ne trouvez pas votre réponse ?",
};
